.myenv/films/urls.py
from django.urls import path
from . import views

app_name = 'films'

urlpatterns = [
    path('', views.FilmListView.as_view(), name='all'),
    path('films/<int:pk>/detail', views.FilmDetailView.as_view(), name='film_detail'),
    path('films/create/', views.FilmCreateView.as_view(), name='film_create'),
    path('films/<int:pk>/update/', views.FilmUpdateView.as_view(), name='film_update'),
    path('films/<int:pk>/delete/', views.FilmDeleteView.as_view(), name='film_delete'),
]

.myenv/films/templates/base.html
<!DOCTYPE HTML>
<html lang="en">

<head>

<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">


{% block title %}
    {% if title %}
        <title>{{title}} | My Films</title>
    {% else %}
        <title>My Films Table</title>
    {% endif %}
{% endblock title %}

{% block head %}
{% endblock head %}

</head>

<body>

<div class="container-fluid">

    <!-- NAVIGATION BAR -->


    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="d-flex justify-content-between px-5 mx-auto" style="width: 80%;">
            <span class="navbar-text text-white">DJANGO C.R.U.D.</span>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link active" href="{% url 'films:all' %}">Films</a>
                </li>

                <!--
                ##
                ## UNCOMMENT THESE LINES IF YOU HAVE A FUNCTIONAL CRUD FOR THE GENRE MODEL
                ## CHANGE ALSO THE URL INFO 'films:all' to 'films:genre_all'

                <li class="nav-item active">
                    <a class="nav-link active" href="{% url 'films:all' %}">Genres</a>
                </li>

                -->

                <li class="nav-item active">
                    <a class="nav-link active" href="https://linktr.ee/fabriciobarbacena" target="_blank">My Social Media</a>
                </li>
            </ul>
        </div>
    </nav>

    <!-- END OF NAVIGATION BAR -->

</div>

{% block content %}
{% endblock content %}


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>

</body>

</html>

.myenv/films/templates/films/film_confirm_delete.html
{% extends "base.html" %}

{% block content %}

{% url 'films:all' as list_all %}

<div class="container d-flex justify-content-center mt-5" style="width: 50%;">
    <div class="col mt-5 text-center">
        <h1 class="mb-5">Delete Film</h1>

        <p class="h5">Are you sure you want to delete the Film:</p>
        <h3 class="my-5">{{ film.title }}</h3>
        <form action="" method="POST">
            {% csrf_token %}
            {% comment %} <input type="submit" value="Confirm">
            <input type="submit" value="Cancel" onclick="window.location='{% url 'films:all' %}'; return false;"> {% endcomment %}
            <input type="submit" class="btn btn-primary btn-lg" value="Confirm" style="margin-right: 30px; margin-top: 30px;">
            <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;" onclick="window.location='{{list_all}}'; return false;" value="Cancel">
        </form>
    </div>
</div>

{% endblock %}

.myenv/films/templates/films/film_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-5" style="width: 70%;">
    <div class="col">
        <h1 class="text-center">Film Details</h1>
        <div class="d-flex justify-content-center">
            <table class="table table-striped mt-5" style="width: 50%">
                <thead>
                    <tr>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                
                    {% for label, value in film.get_fields  %}
                        <tr>
                            <td>{{label | upper}}</td>
                            <td>{{value}}</td>
                        </tr>
                    {% endfor %}
                        
                </tbody>
            </table>
        </div>

        <div class="d-flex justify-content-center">
            <a href="{% url 'films:all' %}" class="d-block btn btn-primary btn-lg my-5">BACK</a>
        </div>
    </div>
        
</div>

{% endblock  %}

.myenv/films/templates/films/film_form.html
{% extends "base.html" %}

{% block content %}

<!-- BOOTSTRAP FORM -->

<div class="container d-flex justify-content-center mt-5" style="width: 25%;">
    <div class="col mt-5">
        <form action="" method="post">
            {% csrf_token %}
            <table class="table">
                {{form.as_table}}
            </table>
            <div class="container d-flex justify-content-center" style="width: 10%;">
                <input type="submit" class="btn btn-primary btn-lg" value="Submit" style="margin-right: 30px; margin-top: 30px;">
                <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;" onclick="window.location='{% url 'films:all' %}'; return false;" value="Cancel">
            </div>    
        </form> 

    </div>
</div>

<!-- END BOOTSTRAP FORM -->

{% endblock %}

.myenv/films/templates/films/film_list.html
{% extends 'base.html' %}

{% block content %}
{% for film in film_list %}
    {% for colname in film.column_set.all  %}
        <p>{{colname}}</p>
    {% endfor %}
{% endfor %}


<div class="container d-flex mt-5" style="width: 70%;">
    <div class="col">
        <h1 class="text-center">My Films</h1>
        <table class="table table-striped mt-5">
            <thead>
                <tr>
                    {% comment %} <th>#</th> {% endcomment %}
                    <th class="text-center" scope="col">Title</th>
                    <th class="text-center" scope="col">Year</th>
                    <th class="text-center" scope="col">Length</th>
                    <th class="text-center" scope="col">Score</th>
                    <th class="text-center" scope="col">Genre</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            
                {% for film in film_list %}
                <tr>
                    {% comment %} <th scope="row">{{forloop.counter}}</th> {% endcomment %}
                    <td class="ml-5"><a href="{% url 'films:film_detail' film.id %}">{{film.title}}</a></td>
                    <td class="text-center">{{film.year}}</td>
                    <td class="text-center">{{film.length}}</td>
                    <td class="text-center">{{film.score | floatformat:2}}</td>
                    <td class="text-center">{{film.genre}}</td>
                    <td><a href="{% url 'films:film_update' film.id %} ">Update</a></td>
                    <td><a href="{% url 'films:film_delete' film.id %}">Delete</a></td>
                </tr>
            {% endfor %}
        
            </tbody>
        </table>    
        <div class="d-flex justify-content-center">
            <a href="{% url 'films:film_create' %}" class="d-block btn btn-primary btn-lg my-5">Add New</a>
        </div>
    </div>
        
</div>

{% endblock content %}